---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://tommykw.github.io/tommykw-hugo/"
title: "Tommykw Hugo Blog Template for GitHub Pages"
---

